---
- name: Playbook de test local
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Afficher un message
      debug:
        msg: "âœ… Ansible fonctionne correctement en local !"
